services:
  - type: web
    name: flask-app
    env: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    plan: free
databases:
  - name: happyfans-db
    plan: free
